Transform: 'AWS::Serverless-2016-10-31'
Resources:
  
  DMWatchAggregatorFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
        Runtime: nodejs8.10
        Handler: index.handler
        CodeUri: ./dist
